services:
  - type: web
    name: api-restful-backend
    env: node
    plan: free
    repo: https://github.com/4lexxe/API_RESTful
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
